# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(help_text='Same as the title, but should only contain Letters,                     Numbers, Underscores or Hyphens. No spaces.', max_length=140)),
                ('publish_date', models.DateTimeField(help_text='The date you want this Post to be published on')),
                ('expire_date', models.DateTimeField(blank=True, help_text='If set, this Post will automatically unpublish from the                     site. It will still be available via Admin Panel.', null=True)),
                ('post', froala_editor.fields.FroalaField(blank=True)),
                ('short_description', models.TextField(blank=True, help_text='2 to 3 scentences that describe the gist of this Post.                     This is what displays when you share the Post on                     Facebook, Twitter...')),
                ('feature_image', models.ImageField(blank=True, help_text='An image that meets OpenGraph specification. Used when                     sharing the Post on Facebook, Twitter... Image size                     should be at least 1200 x 630.', upload_to='parents')),
                ('is_published', models.BooleanField(default=False, help_text='Only Published Posts are displayed publicaly on the site.', verbose_name='Publish on Site')),
                ('is_pinned', models.BooleanField(default=False, help_text='If pinned, this Post will be listed before Posts in                     chronological order.', verbose_name='Pin to top')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, help_text='Automatically updates everytime you click Save.')),
            ],
            options={
                'ordering': ['-is_pinned', '-publish_date'],
                'get_latest_by': 'publish_date',
            },
        ),
    ]
