# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-13 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180211_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, help_text='The category to publish this post under.', null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.PostCategory'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(help_text='The date you want this Post to be published on. Future                     dates will not be visible on the site until day-of.'),
        ),
    ]
