# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=140)),
                ('body', froala_editor.fields.FroalaField(blank=True, help_text='Body should include the bulk of information related to                    the event. Hours, Admission, Contact details.')),
                ('teaser', froala_editor.fields.FroalaField(blank=True, help_text="This copy is cited when there is not enough room to                    display the full body copy. It shouldn't be a direct copy                    & paste, but a summarized verion of the body copy.")),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.TextField(blank=True, help_text='This should comprise of a simple location name (if                    possible),linking to a Google Maps URL. If citing the                    street address itself; do so in the body field.')),
                ('is_featured', models.BooleanField(default=False, help_text='Check this to prioritize visability on the site.', verbose_name='Featured Event')),
                ('is_main_feature', models.BooleanField(default=False, help_text='Checking this will make it the most prominent on                    easttroy.org/events/', verbose_name='Main Feature on Events Homepage')),
                ('is_published', models.BooleanField(default=False, help_text='This event will not display publicly on the site if                    unchecked.', verbose_name='Publish on Site')),
                ('in_calendar', models.BooleanField(default=True, help_text='Uncheck this to keep the event off the site calendar.', verbose_name='Display in Calendar')),
                ('custom_url', models.CharField(blank=True, help_text='If supplied, links to this event will                    point directly to a custom url, opening in a new                    tab/window.', max_length=140)),
                ('display_in_menu', models.BooleanField(default=False, help_text='If checked, this event item will show up under the sites                    global menu\'s "Event" menu item.')),
                ('display_menu_title', models.CharField(blank=True, help_text="You can optionally tailor the title of this event for the                    the purpose of displaying under the global menu's Event                    dropdown.", max_length=75)),
                ('feature_image', models.ImageField(blank=True, help_text='A photo to display along with the                                        event; if appropriate.', upload_to='events', verbose_name='Coverphoto')),
                ('physical_flyer', models.FileField(blank=True, help_text='Sometimes Events have physical flyers. Use this field to                     attach them. All formats allowed, but default to PDF.', upload_to='events/event_flyers')),
                ('sort_order', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-end_date'],
                'get_latest_by': 'start_date',
            },
        ),
    ]
