# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_ditwticketpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ditwticketpurchase',
            name='retain_payment_info',
            field=models.CharField(max_length=3),
        ),
    ]
