# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-08 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180306_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='ditwticketpurchase',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe Customer ID'),
        ),
    ]
