# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-08 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180308_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='ditwticketpurchase',
            name='qrcode_url',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
