# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-08 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20180308_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='ditwticketpurchase',
            name='ticket_enhancer',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
