# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_ditwticketpurchase_ticket_enhancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ditwticketpurchase',
            name='received_manual_payment',
            field=models.BooleanField(default=False, help_text='Check this box if this customer paid by check/on-site and is settled up.', verbose_name='Received Manul Payment'),
        ),
    ]
