# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_ditwticketpurchase_received_manual_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ditwticketpurchase',
            name='last_name',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name='ditwticketpurchase',
            name='paddle',
            field=models.CharField(blank=True, max_length=75, verbose_name='Assigned Paddle ID'),
        ),
        migrations.AddField(
            model_name='ditwticketpurchase',
            name='table',
            field=models.CharField(blank=True, max_length=75, verbose_name='Assigned Table Number'),
        ),
    ]
