# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20180518_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='ditwticketpurchase',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
