# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-14 18:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0031_student_medical_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='administeredmed',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author of note'),
        ),
    ]
