version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    command: bash -c 'python manage.py makemigrations && python manage.py migrate && DJNCI_DEBUG=true DJNCI_GRAPHIQL=true python manage.py runserver 0.0.0.0:9000'
    volumes:
      - .:/djnci
    ports:
      - '9000:9000'
    depends_on:
      - db
