# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-30 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180720_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPublic', models.IntegerField(choices=[(0, 'Private'), (1, 'Public')], default=0)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('size', models.BigIntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uploaded', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('preview_path', models.CharField(blank=True, max_length=120, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_files', to='accounts.School')),
            ],
            options={
                'verbose_name': 'School File',
                'verbose_name_plural': 'School Files',
            },
        ),
    ]
