# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-30 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_schoolfile_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolfile',
            name='active',
        ),
        migrations.RemoveField(
            model_name='schoolfile',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='schoolfile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='schoolfile',
            name='path',
        ),
        migrations.RemoveField(
            model_name='schoolfile',
            name='preview_path',
        ),
        migrations.RemoveField(
            model_name='schoolfile',
            name='size',
        ),
        migrations.RemoveField(
            model_name='schoolfile',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='schoolfile',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='schoolfile',
            name='uploaded',
        ),
        migrations.AddField(
            model_name='schoolfile',
            name='file',
            field=models.FileField(default='', upload_to='media/'),
            preserve_default=False,
        ),
    ]
