# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-30 15:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20190930_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolfile',
            name='file',
            field=models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
