# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-14 18:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import djnci.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20191002_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolfile',
            name='file',
            field=models.FileField(upload_to=djnci.utils.path_and_rename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])]),
        ),
    ]
